fix mac
TileDB-Inc/TileDB-Java pull request #305
Opened 2023-07-26 16:56 UTC by DimitrisStaratzis

2023-07-26 20:17 UTC, ihnorton requested changes
Not sure about the commented windows section?

2023-07-26 20:17 UTC, ihnorton commented on build.gradle
> +//            from file("$tiledbHome/lib/libtiledb.dll") to be tested
?

2023-07-26 22:18 UTC, DimitrisStaratzis commented on build.gradle
> +//            from file("$tiledbHome/lib/libtiledb.dll") to be tested
Yeah, still WIP, changed PR to draft

2023-07-27 13:52 UTC, ihnorton commented on build.gradle
> +            from file("$tiledbHome/lib/libtiledb.so")
Needs `lib64` too

2023-07-27 15:10 UTC, DimitrisStaratzis commented on build.gradle
> +            from file("$tiledbHome/lib/libtiledb.so")
Done

2023-07-27 20:05 UTC, DimitrisStaratzis commented on build.gradle
> +//            from file("$tiledbHome/lib/libtiledb.dll") to be tested
I tested the change in windows

2023-11-21 12:11 UTC, closed without merging